export const MOCK_TEAM_1 = [
  {
    displayName: "Mock Participant 3",
    gender: 1,
    age: 54,
    timeZone: "pst",
    avatarId: 2,
    totalClicks: 3,
  },
  {
    displayName: "Mock Participant 4",
    gender: 0,
    age: 39,
    timeZone: "pst",
    avatarId: 2,
    totalClicks: 0,
  },
  {
    displayName: "Mock Participant 2",
    gender: 1,
    age: 20,
    timeZone: "est",
    avatarId: 2,
    totalClicks: 0,
  },
  {
    displayName: "Mock Participant 6",
    gender: 0,
    age: 64,
    timeZone: "cst",
    avatarId: 2,
    totalClicks: 6,
  },
  {
    displayName: "Mock Participant 5",
    gender: 1,
    age: 22,
    timeZone: "est",
    avatarId: 2,
    totalClicks: 0,
  },
];
