export const MOCK_PARTICIPANT_1 = {
  participantId: 1,
  userId: "mockparticipant1",
  displayName: "Mock Participant 1",
  seedStatus: "value",
  gender: "male",
  age: 41,
  timeZone: "pst",
  killStatus: 0,
  totalRegularBonus: 0,
  totalSeedBonus: 0,
  avatarId: 2,
  totalClicks: 1,
  completePreSurvey: false,
  completeConsentForm: false,
  completePostSurvey: false,
  completeOnboarding: false,
  timeSlot: null,
  basePayment: 0,
  waitingRoomStatus: false,
  chatClient: null,
  activeChannel: null,
  completeExperiment: false,
  preSurveyBonus: 0,
};

export const MOCK_PARTICIPANT_2 = {
  participantId: 2,
  userId: "mockparticipant2",
  displayName: "Mock Participant 2",
  seedStatus: "value",
  gender: "female",
  age: 20,
  timeZone: "est",
  killStatus: 0,
  totalRegularBonus: 0,
  totalSeedBonus: 0,
  avatarId: 2,
  completePreSurvey: true,
  completeConsentForm: false,
  completePostSurvey: false,
  completeOnboarding: false,
  timeSlot: null,
  basePayment: 0,
  waitingRoomStatus: false,
  chatClient: null,
  activeChannel: null,
  completeExperiment: false,
  preSurveyBonus: 0,
};

export const MOCK_PARTICIPANT_3 = {
  participantId: 3,
  userId: "mockparticipant3",
  displayName: "Mock Participant 3",
  seedStatus: "value",
  gender: "female",
  age: 54,
  timeZone: "pst",
  killStatus: 0,
  totalRegularBonus: 0,
  totalSeedBonus: 0,
  avatarId: 2,
  totalClicks: 0,
  completePreSurvey: true,
  completeConsentForm: false,
  completePostSurvey: false,
  completeOnboarding: false,
  timeSlot: null,
  basePayment: 0,
  waitingRoomStatus: false,
  chatClient: null,
  activeChannel: null,
  completeExperiment: false,
  preSurveyBonus: 0,
};

export const MOCK_PARTICIPANT_4 = {
  participantId: 4,
  userId: "mockparticipant4",
  displayName: "Mock Participant 4",
  seedStatus: "value",
  gender: "male",
  age: 39,
  timeZone: "pst",
  killStatus: 0,
  totalRegularBonus: 0,
  totalSeedBonus: 0,
  avatarId: 2,
  totalClicks: 0,
  completePreSurvey: true,
  completeConsentForm: false,
  completePostSurvey: false,
  completeOnboarding: false,
  timeSlot: null,
  basePayment: 0,
  waitingRoomStatus: false,
  chatClient: null,
  activeChannel: null,
  completeExperiment: false,
  preSurveyBonus: 0,
};

export const MOCK_PARTICIPANT_5 = {
  participantId: 5,
  userId: "mockparticipant5",
  displayName: "Mock Participant 5",
  seedStatus: "value",
  gender: "female",
  age: 22,
  timeZone: "est",
  killStatus: 0,
  totalRegularBonus: 0,
  totalSeedBonus: 0,
  avatarId: 2,
  totalClicks: 0,
  completePreSurvey: true,
  completeConsentForm: false,
  completePostSurvey: false,
  completeOnboarding: false,
  timeSlot: null,
  basePayment: 0,
  waitingRoomStatus: false,
  chatClient: null,
  activeChannel: null,
  completeExperiment: false,
  preSurveyBonus: 0,
};

export const MOCK_PARTICIPANT_6 = {
  participantId: 6,
  userId: "mockparticipant6",
  displayName: "Mock Participant 6",
  seedStatus: "value",
  gender: "male",
  age: 64,
  timeZone: "cst",
  killStatus: 0,
  totalRegularBonus: 0,
  totalSeedBonus: 0,
  avatarId: 2,
  totalClicks: 0,
  completePreSurvey: true,
  completeConsentForm: false,
  completePostSurvey: false,
  completeOnboarding: false,
  timeSlot: null,
  basePayment: 0,
  waitingRoomStatus: false,
  chatClient: null,
  activeChannel: null,
  completeExperiment: false,
  preSurveyBonus: 0,
};
